server:
  port: 8084

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # NOTICE THE NEW PREFIX LAYER HERE FOR 5.0.x
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user
              predicates:
                - Path=/users/**
             
app-info :
  name: User Management API
  description: CRUD operations for user management production environment
  version: 1.0.0
  developer:
    name: Your Name
    email: your.email@example.com
  contact:
    name: Support Team
    email: support@test.com

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

info:
  app:
    name: Edge node Service
    description: Api gateway for microservice
    version: 1.0.0
    author: Logesh

logging:
  level:
    # Mutes the RestClient HTTP request/response payloads for Eureka fetches
    org.springframework.web.client.DefaultRestClient: DEBUG
    # Mutes the routing metric updates every 30 seconds
    org.springframework.cloud.gateway.filter.GatewayMetricsFilter: DEBUG
