app-info :
  name: Product Management API
  description: CRUD operations for product management producttion environment
  version: 1.0.0
  developer:
    name: Your Name
    email: your.email@example.com
  contact:
    name: Support Team
    email: support@test.com

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} traceId=%X{trace_id} spanId=%X{span_id} - %msg%n"
